### ISSUE TITLE
make sure to comment main parts of code

### ISSUE THREAD

**Issue by ad3429** [josephjguerra/tea-cozy#2]
https://github.com/josephjguerra/tea-cozy/blob/master/index.html#L8-L77

Make sure to comment the main parts of your HTML in future projects. This becomes increasingly important as your projects become larger and more complex. Here is a quick refresher on commenting in HTML:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/33176033-a1906218-d02b-11e7-84a9-ce2b19473650.png">

**Comment by josephjguerra** [comment]
spacing and comments added for readability
