### ISSUE TITLE
CSS is clean and succinct

### ISSUE THREAD

**Issue by ad3429** [josephjguerra/tea-cozy#4]
https://github.com/josephjguerra/tea-cozy/blob/master/css/styles.css#L1-L120

Your CSS is short, clean and succinct -- make sure to keep it up. An area of improvement is to make sure to comment your main stylings so that it's absolutely clear why you are styling elements a particular way. Here is a quick refresher on commenting in CSS:

<img width="178" alt="css comment" src="https://user-images.githubusercontent.com/25671399/33176126-f8839b4e-d02b-11e7-93a1-727f3120f12c.png">

**Comment by josephjguerra** [comment]
spacing and comments added for readability
